# Deploy to EC2
# Updated: Testing GitHub Actions deployment after security group update

name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: --max_old_space_size=4096
      NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_PRODUCTION_SUPABASE_URL }}
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_PRODUCTION_SUPABASE_ANON_KEY }}
      SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.PRODUCTION_SUPABASE_SERVICE_ROLE_KEY }}
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build application
        run: npm run build

      - name: Setup SSH
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          # Start SSH agent
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          
          # Debug: Show current IP
          echo "Current GitHub Actions IP:"
          curl -s https://api.ipify.org
          
          # Setup SSH key with stricter permissions
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          
          # Add key to agent
          ssh-add ~/.ssh/deploy_key
          
          # Disable strict host key checking for initial connection
          echo "Scanning host key..."
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts 2>/dev/null
          
          # Test connection with 30s timeout
          ssh -o ConnectTimeout=30 ec2-user@${{ secrets.EC2_HOST }} 'echo "SSH connection successful"'
      
      - name: Create env file
        run: |
          cat > .env.production << EOL
          NEXT_PUBLIC_SUPABASE_URL=${{ secrets.NEXT_PUBLIC_PRODUCTION_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY=${{ secrets.NEXT_PUBLIC_PRODUCTION_SUPABASE_ANON_KEY }}
          SUPABASE_SERVICE_ROLE_KEY=${{ secrets.PRODUCTION_SUPABASE_SERVICE_ROLE_KEY }}
          AWS_REGION=${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_BUCKET_NAME=${{ secrets.AWS_BUCKET_NAME }}
          NODE_ENV=production
          EOL

      - name: Deploy to EC2
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          # Create deployment package
          tar -czf deploy.tar.gz \
            .next \
            public \
            app \
            components \
            lib \
            hooks \
            types \
            .env.production \
            next.config.mjs \
            middleware.ts \
            package.json \
            package-lock.json \
            ecosystem.config.js \
            tailwind.config.ts \
            postcss.config.mjs \
            tsconfig.json \
            next-env.d.ts

          # Copy with progress and specific timeout
          scp -o ConnectTimeout=30 deploy.tar.gz ec2-user@${{ secrets.EC2_HOST }}:~
          
          # Deploy with error handling
          ssh -o ConnectTimeout=30 ec2-user@${{ secrets.EC2_HOST }} '
            set -e
            echo "Stopping existing application..."
            pm2 stop chat-genius 2>/dev/null || true
            
            echo "Cleaning up old deployment..."
            rm -rf ~/chat-genius
            mkdir -p ~/chat-genius
            
            echo "Extracting new deployment..."
            tar -xzf deploy.tar.gz -C ~/chat-genius
            cd ~/chat-genius
            
            echo "Installing dependencies..."
            npm ci --production
            
            echo "Starting application..."
            pm2 start npm --name "chat-genius" -- start && pm2 save
            
            echo "Deployment complete!"
          ' 