name: Deploy to EC2

on:
  push:
    branches: [ "main" ]

env:
  AWS_REGION: us-east-1
  EC2_INSTANCE_ID: ${{ secrets.EC2_INSTANCE_ID }}

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::474668398195:role/UnifiedServicesRole
        aws-region: ${{ env.AWS_REGION }}

    - name: Test AWS Connection
      run: |
        echo "Testing AWS Connection..."
        aws sts get-caller-identity
        echo "Testing SSM access..."
        aws ssm describe-instance-information --region us-east-1

    - name: Add Parameters to SSM
      run: |
        aws ssm put-parameter --name "/chat-genius/DATABASE_URL" --value "${{ secrets.DATABASE_URL }}" --type "SecureString" --overwrite
        aws ssm put-parameter --name "/chat-genius/NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY" --value "${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}" --type "SecureString" --overwrite
        aws ssm put-parameter --name "/chat-genius/CLERK_SECRET_KEY" --value "${{ secrets.CLERK_SECRET_KEY }}" --type "SecureString" --overwrite
        aws ssm put-parameter --name "/chat-genius/NEXT_PUBLIC_SUPABASE_URL" --value "${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}" --type "SecureString" --overwrite
        aws ssm put-parameter --name "/chat-genius/NEXT_PUBLIC_SUPABASE_ANON_KEY" --value "${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}" --type "SecureString" --overwrite

    - name: Build Application
      run: |
        npm ci
        npm run build

    - name: Deploy to EC2
      run: |
        echo "Deploying to instance ${{ env.EC2_INSTANCE_ID }}..."
        aws ssm send-command \
          --document-name "AWS-RunShellScript" \
          --targets "Key=instanceids,Values=${{ env.EC2_INSTANCE_ID }}" \
          --parameters 'commands=[
            "cd /home/ec2-user/chat-genius",
            "git pull origin main",
            "npm ci",
            "npm run build",
            "pm2 restart chat-genius || pm2 start npm --name chat-genius -- start"
          ]' 